import React from 'react';
import { OpenSourceContributions } from '../public/data/Contributions';
import { LuExternalLink } from 'react-icons/lu';
import { IoGitPullRequestSharp } from 'react-icons/io5';
import Image from 'next/image';

const Description = ({ title, status, description, link }) => {
  return (
    <div className="mt-16">
      <div className="justify-between text-white border-0 border-red-500 md:flex">
        <div className="flex font-bold text-blue-400 sm1:text-lg md:text-xl">
          <span>{title}</span>
          <span className="mt-1 ml-8">
            <a href={link} target="_blank" rel="noreferrer">
              <LuExternalLink />
            </a>
          </span>
        </div>
        <div className={`p-2 w-fit md:ml-2 text-sm text-white ${status === 'Merged' ? 'bg-[#8957E5]' : 'bg-[#238636]'} rounded-xl flex`}>
          <span className="mt-1 mr-2 text-sm">
            <IoGitPullRequestSharp />
          </span>
          <span>{status}</span>
        </div>
      </div>
      <div className="mt-2">{description}</div>
    </div>
  );
};

const Contributions = () => {
  return (
    <div className="mb-20 text-white">
      <div className="font-extrabold tracking-tighter text-center text-blue-400 sm1:text-xl sm1:p-6 md:pl-20 md:text-6xl">
        Open Source Contributions
      </div>
      <div className="font-extrabold tracking-tighter sm1:text-xl sm1:p-6 md:pl-20">
        About the Organization _
      </div>
      <div className="sm1:p-6 md:p-20 lg:w-4/5 xl:w-3/5">
        <div className="text-5xl font-bold text-blue-400">GA4GH</div>
        <div className="mt-4">
          The Global Alliance for Genomics and Health (GA4GH) aims to develop frameworks and standards for working with health-related and genomic data. Its standards ensure data is interoperable, accessible, and reusable, supporting healthcare practitioners and researchers worldwide in making informed decisions and improving treatments.
          <Image className="mt-10" alt="GA4GH logo" src="/media/contributions/ga4gh.png" height={500} width={500} />
        </div>
      </div>
      <div className="ml-auto sm1:p-6 xl:w-3/5 md:p-20 lg:w-4/5">
        <div className="ml-auto font-bold text-blue-400 sm1:text-2xl md:text-5xl">About Elixir Cloud & AAI</div>
        <div className="md:pr-20">
          ELIXIR Cloud, provided by the European life science infrastructure ELIXIR, offers tools for storing, sharing, and analyzing data generated by life sciences research. AAI (Authentication and Authorization Infrastructure) ensures secure access to these resources, enabling collaboration between researchers while maintaining data privacy.
        </div>
      </div>
      <div className="font-extrabold tracking-tighter text-center text-blue-400 sm1:text-xl sm1:p-6 md:pl-20 md:text-6xl">
        Pull Requests
      </div>
      <div className="m-auto sm1:p-6 md:p-10 lg:p-20 lg:w-4/5 xl:w-3/5 md:mt-0">
        {
          OpenSourceContributions.map((contri) => (
            <Description
              title={contri.title}
              status={contri.status}
              description={contri.description}
              key={contri.id}
              link={contri.link}
            />
          ))
        }
      </div>
    </div>
  );
};

export default Contributions;
